---
name: wf2
on:
  push:
    branches: ["main", "feat/1"]
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo on runner
        uses: actions/checkout@v4
      - name: step1
        run: |
          echo "hi-2"
          echo "jap-2">n1
      - name: step3
        run: >
          echo "hi"
          "mum-1"
          "mum-2"
