---
name: wf7 -> give ip pars when we manually run the wf
on:
  workflow_dispatch:
    inputs:
      i1:
        description: val of i1
        default: 1
        #true means ip par is required to run the wf
        required: true
      i2:
        description: "val of i2"
        default: 2
        required: true
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: clone the git lr on runner, runner is a vm where wf runs
        uses: actions/checkout@v4
      - name: calc
        #it is a unique identifier for step and is used along with steps context to give the step ref
        id: id1
        run: echo "::set-output name=op1::$((${{inputs.i1}}+${{inputs.i2}}))"
      - name: step2
        run: echo "sum of ${{inputs.i1}} and ${{inputs.i2}} is ${{steps.id1.outputs.op1}}"
